import { runConfigScript } from "../configRuntime";
import { FEATURE_FLAG_SPECS } from "../helpers/featureFlagSpecs";
import { verifyFeatureFlagStates } from "./verifyFeatureFlagStates";

export async function runVerifyFeaturesState() {
  await verifyFeatureFlagStates([
    FEATURE_FLAG_SPECS.CANCEL_SHIFT_FEATURE_DISABLED,
    FEATURE_FLAG_SPECS.CREATE_ORDER_FEATURE_DISABLED_LIMIT_DECREASE,
    FEATURE_FLAG_SPECS.CREATE_ORDER_FEATURE_DISABLED_LIMIT_INCREASE,
    FEATURE_FLAG_SPECS.CREATE_ORDER_FEATURE_DISABLED_LIMIT_SWAP,
    FEATURE_FLAG_SPECS.CREATE_ORDER_FEATURE_DISABLED_MARKET_SWAP,
    FEATURE_FLAG_SPECS.CREATE_ORDER_FEATURE_DISABLED_STOP_LOSS_DECREASE,
    FEATURE_FLAG_SPECS.CREATE_SHIFT_FEATURE_DISABLED,
    FEATURE_FLAG_SPECS.EXECUTE_ATOMIC_WITHDRAWAL_FEATURE_DISABLED,
    FEATURE_FLAG_SPECS.EXECUTE_ORDER_FEATURE_DISABLED_LIMIT_DECREASE,
    FEATURE_FLAG_SPECS.EXECUTE_ORDER_FEATURE_DISABLED_LIMIT_INCREASE,
    FEATURE_FLAG_SPECS.EXECUTE_ORDER_FEATURE_DISABLED_LIMIT_SWAP,
    FEATURE_FLAG_SPECS.EXECUTE_ORDER_FEATURE_DISABLED_MARKET_SWAP,
    FEATURE_FLAG_SPECS.EXECUTE_ORDER_FEATURE_DISABLED_STOP_LOSS_DECREASE,
    FEATURE_FLAG_SPECS.EXECUTE_SHIFT_FEATURE_DISABLED,
    FEATURE_FLAG_SPECS.GASLESS_FEATURE_DISABLED,
    FEATURE_FLAG_SPECS.JIT_FEATURE_DISABLED,
    FEATURE_FLAG_SPECS.SUBACCOUNT_FEATURE_DISABLED,
  ]);
}

if (require.main === module) {
  runConfigScript(runVerifyFeaturesState);
}
