name: CI
on:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - run: pnpm install --ignore-scripts
        shell: bash
      - name: Check cyclic dependencies
        run: pnpm hardhat run scripts/cyclicDependencyCheck.ts
        shell: bash
      - name: Check contract sizing
        continue-on-error: true # to show errors as warnings
        run: pnpm hardhat measure-contract-sizes
        shell: bash
      - name: Run Tests
        run: pnpm hardhat test
        shell: bash
